apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: vm-pubkey
    namespace: vm
    literals:
      - key1=<path:kv/data/vm#pub_key>

resources:
  - namespace.yaml
  - storageclass.yaml
  - networkattachmentdefinition.yaml
  - datavolume.yaml
  - virtualmachine.yaml
  - service.yaml
