apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: cloudinit
    namespace: vm
    files:
      - userData=bw-secrets/vm-userdata.yaml
      - networkData=bw-secrets/vm-networkdata.yaml
  - name: vm-pubkey
    namespace: vm
    files:
      - key1=bw-secrets/vm-pubkey.pub

resources:
  - namespace.yaml
  - storageclass.yaml
  - networkattachmentdefinition.yaml
  - datavolume.yaml
  - virtualmachine.yaml
  - service.yaml
