apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vm-bridge
  namespace: vm
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "vm-bridge",
      "type": "bridge",
      "bridge": "br0",
      "ipam": {
          "type": "host-local",
          "subnet": "192.168.1.0/24"
      }
    }
