apiVersion: v1
kind: Service
metadata:
  name: vm-ssh
  namespace: vm
spec:
  type: NodePort
  selector:
    kubevirt.io/domain: vm
  ports:
  - nodePort: 30422
    port: 22
    protocol: TCP
    targetPort: 22
