apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/os: linux
  name: vm
  namespace: vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm
    spec:
      hostname: vm
      domain:
        cpu:
          cores: 1
        memory:
          guest: 4Gi
        devices:
          disks:
            - disk:
                bus: virtio
              name: disk0
              bootOrder: 1
            - cdrom:
                bus: sata
                readonly: true
              name: cloudinitdisk
              bootOrder: 2
          interfaces:
            - name: default
              masquerade: {}
              bootOrder: 3
            # - name: vm
            #   bridge: {}
            #   bootOrder: 4
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: "1"
            memory: 4Gi
      networks:
        - name: default
          pod: {}
        # - name: vm
        #   multus:
        #     networkName: vm-bridge
      volumes:
        - name: disk0
          ephemeral:
            persistentVolumeClaim:
              claimName: ubuntu-image-2404
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: vm
              users:
                - name: remi
                  ssh_import_id:
                    - gh:remikeat
                  passwd: <path:kv/data/vm#password>
                  lock_passwd: False
                  shell: /bin/bash
                  sudo: ALL=(ALL) ALL
              ssh_pwauth: false
              disable_root: false
            networkData: |
              version: 2
              ethernets:
                enp1s0:
                  dhcp4: true
              #  enp2s0:
              #    dhcp4: false
              #    addresses: [192.168.1.100/22]
              #    gateway4: 192.168.0.1
      accessCredentials:
      - sshPublicKey:
          source:
            secret:
              secretName: vm-pubkey
          propagationMethod:
            qemuGuestAgent:
              users:
              - remi
