apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/os: linux
  name: vm
  namespace: vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm
    spec:
      hostname: vm
      domain:
        cpu:
          cores: 1
        memory:
          guest: 4Gi
        devices:
          disks:
            - disk:
                bus: virtio
              name: disk0
              bootOrder: 1
            - cdrom:
                bus: sata
                readonly: true
              name: cloudinitdisk
              bootOrder: 2
          interfaces:
            - name: default
              masquerade: {}
              bootOrder: 3
            - name: vm
              bridge: {}
              bootOrder: 4
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: "1"
            memory: 4Gi
      networks:
        - name: default
          pod: {}
        - name: vm
          multus:
            networkName: vm/vm-bridge
      volumes:
        - name: disk0
          ephemeral:
            persistentVolumeClaim:
              claimName: ubuntu-image-2404
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: cloudinit
      accessCredentials:
      - sshPublicKey:
          source:
            secret:
              secretName: vm-pubkey
          propagationMethod:
            qemuGuestAgent:
              users:
              - remi
