apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent
  namespace: argo-cd
spec:
  project: default
  sources:
    - repoURL: https://fluent.github.io/helm-charts
      targetRevision: 3.1.0
      chart: fluent-operator
      helm:
        valueFiles:
          - $repo/argocd/applications/fluent/values.yaml
    - repoURL: https://github.com/remikeat/cluster.git
      targetRevision: HEAD
      ref: repo
  destination:
    server: https://kubernetes.default.svc
    namespace: fluent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
