containerRuntime: containerd
fluentbit:
  crdsEnable: false
  enable: true
  output:
    es:
      enable: false
      host: elasticsearch-es-http.default
      httpUser:
        value: elastic
fluentd:
  crdsEnable: false
  enable: false
  output:
    es:
      enable: false
      host: elasticsearch-es-http.default
      httpUser:
        value: elastic
