containerRuntime: containerd
fluentbit:
  crdsEnable: false
  enable: true
  output:
    es:
      enable: false
      host: elasticsearch-es-http.default
      httpPassword:
        valueFrom:
          secretKeyRef:
            name: elasticsearch-es-elastic-user
            key: elastic
      httpUser:
        valueFrom:
          secretKeyRef:
            name: elasticsearch-username
            key: username
fluentd:
  crdsEnable: false
  enable: false
  output:
    es:
      enable: false
      host: elasticsearch-es-http.default
      httpPassword:
        valueFrom:
          secretKeyRef:
            name: elasticsearch-es-elastic-user
            key: elastic
      httpUser:
        valueFrom:
          secretKeyRef:
            name: elasticsearch-username
            key: username
