apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: camel-k
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/remikeat/cluster.git
    targetRevision: HEAD
    path: argocd/pipelines/camel-k/kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: camel-k
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
