apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: harbor-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths":{
              "harbor.remikeat.com":{
                "username":"{{index (.user | fromYaml) "username"}}",
                "password":"{{index (.user | fromYaml) "password"}}",
                "auth":"{{ printf "%s:%s" (index (.user | fromYaml) "username") (index (.user | fromYaml) "password") | b64enc }}"
              }
            }
          }
  dataFrom:
  - extract:
      key: infra/storage/harbor
