apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: camel-k
    namespace: camel-k
    releaseName: camel-k
    valuesFile: values.yaml
    version: 2.4.0
    repo: https://apache.github.io/camel-k/charts/
    includeCRDs: true

resources:
  - externalsecret.yaml
