apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-setup-index-template-
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
        - name: setup-index-template
          image: curlimages/curl
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-es-elastic-user
                  key: elastic
          command: ["sh", "-c"]
          args:
            - |
              curl -u "elastic:$PASSWORD" -X PUT -L https://elasticsearch.remikeat.com/_index_template/single_node_template -H "Content-Type: application/json" -d '{"index_patterns": ["*"],"priority": 2, "template": {"settings": {"number_of_shards": 1,"number_of_replicas": 0}}}'
      restartPolicy: Never
  backoffLimit: 2
