apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      imagePullSecrets:
        - name: harbor-credentials
      containers:
        - name: strapi
          image: <path:kv/data/infra/storage/harbor#hostname>/library/strapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 1337
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 1000m
              memory: 4Gi
          volumeMounts:
            - name: strapi-storage
              mountPath: /opt/app/public/uploads
            - name: yarn-cache
              mountPath: /tmp
          env:
            - name: HOST
              value: 0.0.0.0
            - name: PORT
              value: "1337"
            - name: NODE_ENV
              value: production
            - name: DATABASE_CLIENT
              value: postgres
            - name: DATABASE_HOST
              value: strapi-db-cluster-rw.strapi.svc.cluster.local
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USERNAME
              value: strapi
            - name: DATABASE_NAME
              value: strapi
            - name: DATABASE_SSL
              value: "false"
          envFrom:
            - secretRef:
                name: strapi
      volumes:
        - name: strapi-storage
          persistentVolumeClaim:
            claimName: strapi-pvc
        - name: yarn-cache
          emptyDir: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: strapi-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
