apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: strapi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: strapi
    creationPolicy: Owner
    template:
      data:
        DATABASE_PASSWORD: "{{.db_password}}"
        APP_KEYS: "{{.app_keys}}"
        API_TOKEN_SALT: "{{.api_token_salt}}"
        ADMIN_JWT_SECRET: "{{.admin_jwt_secret}}"
        TRANSFER_TOKEN_SALT: "{{.transfer_token_salt}}"
  dataFrom:
  - extract:
      key: infra/strapi
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: strapi-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: strapi-credentials
    creationPolicy: Owner
    template:
      data:
        username: strapi
        password: "{{.db_password}}"
  dataFrom:
  - extract:
      key: infra/strapi
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docker-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: docker-config
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths":{
              "harbor.remikeat.com":{
                "username":"{{index (.user | fromYaml) "username"}}",
                "password":"{{index (.user | fromYaml) "password"}}",
                "auth":"{{ printf "%s:%s" (index (.user | fromYaml) "username") (index (.user | fromYaml) "password") | b64enc }}"
              }
            }
          }
  dataFrom:
  - extract:
      key: infra/harbor
