apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubevirt/kubevirt/releases/download/v1.3.1/kubevirt-operator.yaml
  - https://github.com/kubevirt/kubevirt/releases/download/v1.3.1/kubevirt-cr.yaml
  - https://github.com/kubernetes-csi/external-snapshotter.git//client/config/crd?ref=release-4.0
  - https://github.com/kubernetes-csi/external-snapshotter.git//deploy/kubernetes/snapshot-controller?ref=release-4.0
