server:
  dataStorage:
    enabled: true
    storageClass: longhorn
  auditStorage:
    enabled: true
    storageClass: longhorn
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: tailscale
    hosts:
      - host: vault
    tls:
     - secretName: vault-tls
       hosts:
         - vault
  standalone:
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "raft" {
        path = "/vault/data"
      }
