server:
  dataStorage:
    enabled: true
    storageClass: longhorn
  auditStorage:
    enabled: true
    storageClass: longhorn
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: tailscale
    hosts:
      - host: vault
    tls:
     - secretName: vault-tls
       hosts:
         - vault
