apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: community-operator
    namespace: mongodb
    releaseName: community-operator
    valuesFile: values-op.yaml
    version: 0.11.0
    repo: https://mongodb.github.io/helm-charts
