apiVersion: v1
kind: ConfigMap
metadata:
  name: config-tracing
  namespace: knative-eventing
data:
  backend: zipkin
  zipkin-endpoint: http://otel-collector-collector.open-telemetry:9411/api/v2/spans
  sample-rate: "0.1"
  debug: "true"
