apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: bitwarden-secret
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  organizationId: "691f9caf-162c-468d-81ae-b1cb00f1872c"
  secretName: helm-values
  map:
    - bwSecretId: 5c30efbe-285f-4b98-ac45-b1cb00f2a86e
      secretKeyName: grafana.yaml
  authToken:
    secretName: bw-auth-token
    secretKey: token
