cr:
  create: true
  namespace: istio-system
  spec:
    auth:
      strategy: "anonymous"
    deployment:
      ingress:
        enabled: true
        class_name: "tailscale"
        override_yaml:
          spec:
            ingressClassName: tailscale
            rules:
              - http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: kiali
                          port:
                            number: 20001
            tls:
              - hosts:
                  - "kiali"
    external_services:
      grafana:
        enabled: true
        in_cluster_url: 'http://kube-prometheus-stack-grafana.kube-prometheus-stack:3000/'
        url: 'https://grafana.remikeat.com'
      prometheus:
        url: "http://kube-prometheus-stack-prometheus.kube-prometheus-stack:9090/"
