cr:
  create: true
  namespace: istio-system
  spec:
    auth:
      strategy: "anonymous"
    deployment:
      service_annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "kiali"
