harborAdminPassword: <path:kv/data/harbor#user | yamlParse | jsonPath {.password}>
expose:
  ingress:
    hosts:
      core: harbor.remikeat.com
    className: kong
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
  tls:
    certSource: secret
    secret:
      secretName: harbor-tls
externalURL: https://harbor.remikeat.com
database:
  internal:
    password: <path:kv/data/harbor#db_password>
registry:
  credentials:
    username: <path:kv/data/harbor#registry_user | yamlParse | jsonPath {.username}>
    password: <path:kv/data/harbor#registry_user | yamlParse | jsonPath {.password}>
secretKey: <path:kv/data/harbor#secret_key>
# nginx:
#   image:
#     repository: ghcr.io/octohelm/harbor/nginx-photon
#     tag: v2.11.0
# portal:
#   image:
#     repository: ghcr.io/octohelm/harbor/harbor-portal
#     tag: v2.11.0
# core:
#   image:
#     repository: ghcr.io/octohelm/harbor/harbor-core
#     tag: v2.11.0
# jobservice:
#   image:
#     repository: ghcr.io/octohelm/harbor/harbor-jobservice
#     tag: v2.11.0
# registry:
#   registry:
#     image:
#       repository: ghcr.io/octohelm/harbor/registry-photon
#       tag: v2.11.0
#   controller:
#     image:
#       repository: ghcr.io/octohelm/harbor/harbor-registryctl
#       tag: v2.11.0
# trivy:
#   image:
#     repository: ghcr.io/octohelm/harbor/trivy-adapter-photon
#     tag: v2.11.0
# database:
#   internal:
#     image:
#       repository: ghcr.io/octohelm/harbor/harbor-db
#       tag: v2.11.0
# redis:
#   internal:
#     image:
#       repository: ghcr.io/octohelm/harbor/redis-photon
#       tag: v2.11.0
# exporter:
#   image:
#     repository: ghcr.io/octohelm/harbor/harbor-exporter
#     tag: v2.11.0
