apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: github-com
    type: kubernetes.io/dockerconfigjson
    files:
    - .dockerconfigjson
  - name: remikeat-com-secrets
    type: kubernetes.io/opaque
    envs:
    - .env
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
