apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: auth-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app: kubevirt-manager
          kubevirt-manager.io/version: 1.4.0
          kubevirt-manager.io/managed: "true"
      data:
        .htpasswd: "{{.htpasswd}}"
  dataFrom:
  - extract:
      key: infra/vm/kubevirt-manager
