apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kong-cluster-cert
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: kong-cluster-cert
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{.certificate}}"
        tls.key: "{{.private_key}}"
  dataFrom:
  - extract:
      key: infra/kong
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kong-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: kong-credentials
    creationPolicy: Owner
    template:
      data:
        username: kong
        password: "{{.pg_password}}"
  dataFrom:
  - extract:
      key: infra/kong
