apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: auth
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
config:
  introspect_url: http://keycloak-service.keycloak.svc.cluster.local:8080/auth/realms/users/protocol/openid-connect/token/introspect
  client_id: <path:kv/data/kong#client_id>
  client_secret: <path:kv/data/kong#client_secret>
plugin: auth
