apiVersion: remikeat.com/v1
kind: GitGenerator
metadata:
  name: kong
  annotations:
    config.kubernetes.io/function: |
      exec: 
        path: ./git-generator.sh
spec:
  repoURL: https://github.com/openappsec/openappsec.git
  path: build_system/charts/open-appsec-kong
  targetRevision: 1.1.18
  patch: fix.patch
  valuesFile: values.yaml
  name: kong
  namespace: kong
  skipCrds: false
  apiVersions:
    - gateway.networking.k8s.io/v1
    - networking.internal.knative.dev/v1alpha1
