apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: kong-enterprise-license
    namespace: kong
    literals:
      - license="'{}'"
  - name: kong-cluster-cert
    namespace: kong
    literals:
      - tls.crt=<path:kv/data/kong#certificate>
      - tls.key=<path:kv/data/kong#private_key>

helmCharts:
  - name: kong
    namespace: kong
    releaseName: kong-cp
    valuesFile: values-cp.yaml
    version: 2.42.0
    repo: https://charts.konghq.com
    includeCRDs: true
    apiVersions:
      - gateway.networking.k8s.io/v1
  - name: kong
    namespace: kong
    releaseName: kong-dp
    valuesFile: values-dp.yaml
    version: 2.42.0
    repo: https://charts.konghq.com

resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/standard-install.yaml
  - gatewayclass.yaml
  - gateway.yaml

patches:
  - target:
      kind: Secret
      name: kong-cluster-cert
    patch: |-
      - op: add
        path: /type
        value: kubernetes.io/tls
