apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: kong-enterprise-license
    namespace: kong
    literals:
      - license="'{}'"

configMapGenerator:
  - name: kong-plugin-auth
    files:
      - kong-plugin-auth/handler.lua
      - kong-plugin-auth/schema.lua

helmCharts:
  - name: cluster
    namespace: kong
    releaseName: kongdb
    valuesFile: values-kongdb.yaml
    version: 0.0.11
    repo: https://cloudnative-pg.github.io/charts

resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/standard-install.yaml
  - gatewayclass.yaml
  - gateway.yaml
  - kongclusterplugin.yaml
  - externalsecret.yaml

generators:
  - kong.yaml
