apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: kong-enterprise-license
    namespace: kong
    literals:
      - license="'{}'"

configMapGenerator:
  - name: kong-plugin-auth
    files:
      - kong-plugin-auth/handler.lua
      - kong-plugin-auth/schema.lua

# helmCharts:
#   - name: cluster
#     namespace: kong
#     releaseName: kongdb
#     valuesFile: values-kongdb.yaml
#     version: 0.0.11
#     repo: https://cloudnative-pg.github.io/charts

resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/standard-install.yaml
  - https://raw.githubusercontent.com/openappsec/openappsec/refs/tags/1.1.18/build_system/charts/open-appsec-kong/crds/crd-openappsec-custom-response.yaml
  - https://raw.githubusercontent.com/openappsec/openappsec/refs/tags/1.1.18/build_system/charts/open-appsec-kong/crds/crd-openappsec-exception.yaml
  - https://raw.githubusercontent.com/openappsec/openappsec/refs/tags/1.1.18/build_system/charts/open-appsec-kong/crds/crd-openappsec-log-trigger.yaml
  - https://raw.githubusercontent.com/openappsec/openappsec/refs/tags/1.1.18/build_system/charts/open-appsec-kong/crds/crd-openappsec-policy.yaml
  - https://raw.githubusercontent.com/openappsec/openappsec/refs/tags/1.1.18/build_system/charts/open-appsec-kong/crds/crd-openappsec-practice.yaml
  - https://raw.githubusercontent.com/openappsec/openappsec/refs/tags/1.1.18/build_system/charts/open-appsec-kong/crds/crd-openappsec-sources-identifier.yaml
  - https://raw.githubusercontent.com/openappsec/openappsec/refs/tags/1.1.18/build_system/charts/open-appsec-kong/crds/crd-openappsec-trusted-sources.yaml
  - https://raw.githubusercontent.com/openappsec/openappsec/refs/tags/1.1.18/build_system/charts/open-appsec-kong/crds/custom-resource-definitions.yaml
  - gatewayclass.yaml
  - gateway.yaml
  - kongclusterplugin.yaml
  - externalsecret.yaml
  - exception.yaml

generators:
  - kong.yaml
