kind: Vanilla

ingressController:
  enabled: true
  image:
    tag: "2.12.6"
  env:
    publish_service: kong/kong-open-appsec-kong-proxy
    feature_gates: Knative=true
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

resources:
  limits:
    cpu: '4'
    memory: 4G
  requests:
    cpu: 100m
    memory: 500m

autoscaling:
  enabled: true

image:
  repository: kong
  tag: "3.8.0"

secretVolumes:
  - kong-cluster-cert

env:
  cluster_control_plane: kong-open-appsec-kong-cluster.kong.svc.cluster.local:8005
  cluster_telemetry_endpoint: kong-open-appsec-kong-clustertelemetry.kong.svc.cluster.local:8006

  lua_ssl_trusted_certificate: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key

  database: "off"

  password: <path:kv/data/infra/core/kong#password>

  admin_gui_url: https://kong-manager.tail4d334.ts.net
  admin_gui_api_url: https://kong-admin.tail4d334.ts.net
  admin_gui_session_conf: '{"secret":"secret","storage":"kong","cookie_secure":false}'

  plugins: bundled,auth

enterprise:
  enabled: false
  license_secret: kong-enterprise-license
  rbac:
    enabled: true
    admin_gui_auth: basic-auth

admin:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false
  ingress:
    enabled: true
    hostname: kong-admin
    path: /
    pathType: Prefix
    ingressClassName: tailscale
    tls: kong-admin-tls

cluster:
  enabled: true
  tls:
    enabled: true

clustertelemetry:
  enabled: true
  tls:
    enabled: true

manager:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false

  ingress:
    enabled: true
    hostname: kong-manager
    path: /
    pathType: Prefix
    ingressClassName: tailscale
    tls: kong-manager-tls

proxy:
  enabled: true
  annotations:
    "lbipam.cilium.io/ips": "192.168.1.1"

plugins:
  configMaps:
    - name: kong-plugin-auth
      pluginName: auth

deployment:
  prefixDir:
    sizeLimit: 1Gi

appsec:
  persistence:
    enabled: true
  userEmail: <path:kv/data/infra/core/open-appsec#email>
  agentToken: <path:kv/data/infra/core/open-appsec#token>
  configMapContent:
    crowdsec:
      enabled: true
      mode: prevent
      logging: enabled
      api:
        url: http://crowdsec-service.crowdsec:8080/v1/decisions/stream
      auth:
        method: apikey
  secretName: appsec-settings-secret
  secretContent:
    crowdsec:
      auth:
        data: <path:kv/data/infra/monitoring/crowdsec#bouncer_key>
