ingressController:
  enabled: false
   
image:
  repository: kong
  tag: "3.8.0"

secretVolumes:
  - kong-cluster-cert
   
env:
  role: data_plane
  database: "off"
   
  cluster_control_plane: kong-cp-kong-cluster.kong.svc.cluster.local:8005
  cluster_telemetry_endpoint: kong-cp-kong-clustertelemetry.kong.svc.cluster.local:8006
   
  lua_ssl_trusted_certificate: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key

enterprise:
  enabled: false
  license_secret: kong-enterprise-license

proxy:
  enabled: true

admin:
  enabled: false
   
manager:
  enabled: false
