ingressController:
  enabled: true
  env:
    publish_service: kong/kong-open-appsec-kong-proxy
    feature_gates: Knative=true

image:
  repository: kong
  tag: "3.8.0"

secretVolumes:
  - kong-cluster-cert

env:
  cluster_control_plane: kong-open-appsec-kong-cluster.kong.svc.cluster.local:8005
  cluster_telemetry_endpoint: kong-open-appsec-kong-clustertelemetry.kong.svc.cluster.local:8006

  lua_ssl_trusted_certificate: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key

  database: postgres
  pg_database: kong
  pg_user: kong
  pg_password: <path:kv/data/infra/kong#pg_password>
  pg_host: 	kongdb-cluster-rw.kong.svc.cluster.local
  pg_ssl: "on"

  password: <path:kv/data/infra/kong#password>

  admin_gui_url: https://kong-manager.tail4d334.ts.net
  admin_gui_api_url: https://kong-admin.tail4d334.ts.net
  admin_gui_session_conf: '{"secret":"secret","storage":"kong","cookie_secure":false}'

  plugins: bundled,auth

enterprise:
  enabled: false
  license_secret: kong-enterprise-license
  rbac:
    enabled: true
    admin_gui_auth: basic-auth

admin:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false
  ingress:
    enabled: true
    hostname: kong-admin
    path: /
    pathType: Prefix
    ingressClassName: tailscale
    tls: kong-admin-tls

cluster:
  enabled: true
  tls:
    enabled: true

clustertelemetry:
  enabled: true
  tls:
    enabled: true

manager:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false
     
  ingress:
    enabled: true
    hostname: kong-manager
    path: /
    pathType: Prefix
    ingressClassName: tailscale
    tls: kong-manager-tls

proxy:
  enabled: true
  annotations:
    "lbipam.cilium.io/ips": "192.168.1.1"

plugins:
  configMaps:
    - name: kong-plugin-auth
      pluginName: auth

appsec:
  persistence:
    enabled: true
  userEmail: <path:kv/data/infra/open-appsec#email>
  agentToken: <path:kv/data/infra/open-appsec#token>
  configMapContent:
    crowdsec:
      enabled: true
      mode: prevent
      logging: enabled
      api:
        url: http://crowdsec-service.crowdsec:8080/v1/decisions/stream
      auth:
        method: apikey
  secretName: appsec-settings-secret
  secretContent:
    crowdsec:
      auth:
        data: <path:kv/data/infra/crowdsec#bouncer_key>
