ingressController:
  enabled: true
  env:
    publish_service: kong/kong-dp-kong-proxy

image:
  repository: kong
  tag: "3.8.0"

secretVolumes:
  - kong-cluster-cert

env:
  role: control_plane
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key

  database: postgres
  pg_database: kong
  pg_user: kong
  pg_password: <path:kv/data/kong#pg_password>
  pg_host: 	kongdb-cluster-rw.cnpg-database.svc.cluster.local
  pg_ssl: "on"

  password: <path:kv/data/kong#password>

  admin_gui_url: https://kong-manager.tail4d334.ts.net
  admin_gui_api_url: https://kong-admin.tail4d334.ts.net
  admin_gui_session_conf: '{"secret":"secret","storage":"kong","cookie_secure":false}'

  plugins: auth

enterprise:
  enabled: false
  license_secret: kong-enterprise-license
  rbac:
    enabled: true
    admin_gui_auth: basic-auth

admin:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false
  ingress:
    enabled: true
    hostname: kong-admin
    path: /
    pathType: Prefix
    ingressClassName: tailscale
    tls: kong-admin-tls

cluster:
  enabled: true
  tls:
    enabled: true

clustertelemetry:
  enabled: true
  tls:
    enabled: true

manager:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false
     
  ingress:
    enabled: true
    hostname: kong-manager
    path: /
    pathType: Prefix
    ingressClassName: tailscale
    tls: kong-manager-tls

proxy:
  enabled: false
