apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://portainer.github.io/k8s/
      targetRevision: 1.0.51
      chart: portainer
      helm:
        valueFiles:
          - $repo/argocd/portainer/values.yaml
    - repoURL: https://github.com/remikeat/cluster.git
      targetRevision: HEAD
      ref: repo
  destination:
    server: https://kubernetes.default.svc
    namespace: portainer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
