global:
  domain: "argocd.remikeat.com"
configs:
  params:
    server:
      insecure: true
server:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-production"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    extraTls:
      - hosts:
          - "argocd.remikeat.com"
        secretName: "argocd-tls"
repoServer:
  volumes:
    - name: bw-secrets
      secret:
        secretName: bw-secrets
        optional: true
    - name: custom-cmp-config
      configMap:
        name: custom-cmp-config
    - name: cmp-tmp
      emptyDir: {}
    - name: custom-tools
      emptyDir: {}
    - name: repo
      emptyDir: {}
    - name: git-askpass
      configMap:
        name: git-askpass
        defaultMode: 0555
        items:
          - key: git_askpass.sh
            path: git_askpass.sh
    - name: template
      configMap:
        name: template
        defaultMode: 0555
        items:
          - key: template.sh
            path: template.sh
    - name: values
      configMap:
        name: values
        defaultMode: 0555
        items:
          - key: values.sh
            path: values.sh
  initContainers:
    - name: download-tools
      image: alpine:3.20
      command: [sh, -c]
      args:
        - wget -q https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-arm64 &&
          chmod +x jq-linux-arm64 &&
          mv jq-linux-arm64 /custom-tools/jq
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
  extraContainers:
    - name: custom-cmp
      command:
        - "/var/run/argocd/argocd-cmp-server"
      image: ghcr.io/remikeat/cluster:latest
      env:
        - name: GIT_ASKPASS
          value: /usr/local/bin/git_askpass.sh
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: github-https
              key: username
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-https
              key: password
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - name: git-askpass
          mountPath: /usr/local/bin/git_askpass.sh
          subPath: git_askpass.sh
        - name: values
          mountPath: /usr/local/bin/values.sh
          subPath: values.sh
        - name: template
          mountPath: /usr/local/bin/template.sh
          subPath: template.sh
        - mountPath: /usr/local/bin/jq
          name: custom-tools
          subPath: jq
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          name: custom-cmp-config
          subPath: plugin.yaml
        - mountPath: /tmp
          name: cmp-tmp
        - mountPath: /bw-secrets
          name: bw-secrets
        - mountPath: /repo
          name: repo
  imagePullSecrets:
    - name: github-registry
