apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: longhorn
    namespace: longhorn-system
    releaseName: longhorn
    valuesFile: values.yaml
    version: 1.6.2
    repo: https://charts.longhorn.io

resources:
  - namespace.yaml
