preUpgradeChecker:
  jobEnabled: false
persistence:
  defaultClassReplicaCount: 1
ingress:
  enabled: true
  ingressClassName: tailscale
  host: longhorn
  tls: true
defaultSettings:
  guaranteedInstanceManagerCPU: 3
  v2DataEngineGuaranteedInstanceManagerCPU: 500
