apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnativepg-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: 0.22.0
      chart: cloudnative-pg
      helm:
        valueFiles:
          - $repo/argocd/storage/cloudnativepg/values-op.yaml
    - repoURL: https://github.com/remikeat/cluster.git
      targetRevision: HEAD
      ref: repo
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
