apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cloudnative-pg
    namespace: cnpg-system
    releaseName: cloudnative-pg
    valuesFile: values-op.yaml
    version: 0.22.0
    repo: https://cloudnative-pg.github.io/charts

resources:
  - namespace.yaml
