apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: kong-credentials
    namespace: cnpg-database
    literals:
      - username=kong
      - password=<path:kv/data/kong#pg_password>

helmCharts:
  - name: cluster
    namespace: cnpg-database
    releaseName: cnpg
    valuesFile: values-db.yaml
    version: 0.0.11
    repo: https://cloudnative-pg.github.io/charts

resources:
  - namespace.yaml
  - application.yaml
