apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: kong-credentials
    namespace: cnpg-database
    literals:
      - username=kong
      - password=<path:kv/data/kong#pg_password>
  - name: keycloak-credentials
    namespace: cnpg-database
    literals:
      - username=keycloak
      - password=<path:kv/data/keycloak#pg_password>

helmCharts:
  - name: kongdb
    namespace: cnpg-database
    releaseName: kongdb
    valuesFile: values-kongdb.yaml
    version: 0.0.11
    repo: https://cloudnative-pg.github.io/charts
  - name: keycloakdb
    namespace: cnpg-database
    releaseName: keycloakdb
    valuesFile: values-keycloakdb.yaml
    version: 0.0.11
    repo: https://cloudnative-pg.github.io/charts

resources:
  - namespace.yaml
  - application.yaml
