apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: kong-credentials
    namespace: cnpg-database
    literals:
      - username=kong
      - password=<path:kv/data/kong#pg_password>

helmCharts:
  - name: cloudnative-pg
    namespace: cnpg-system
    releaseName: cnpg
    version: 0.22.0
    repo: https://cloudnative-pg.github.io/charts
  - name: cluster
    namespace: cnpg-database
    releaseName: cnpg
    valuesFile: values.yaml
    version: 0.0.11
    repo: https://cloudnative-pg.github.io/charts
