type: postgresql
mode: standalone
version:
  postgresql: "16"
cluster:
  instances: 1
  roles:
    - name: kong
      connectionLimit: -1
      ensure: present
      comment: Kong user
      login: true
      inherit: true
      superuser: true
      passwordSecret:
        name: kong-credentials
  initdb:
    database: kong
    owner: kong
    secret:
      name: kong-credentials
    encoding: UTF8
backups:
  enabled: false
