apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: falco
    namespace: falco
    releaseName: falco
    valuesFile: values.yaml
    version: 4.8.2
    repo: https://falcosecurity.github.io/charts

resources:
  - fluent.yaml
  - ingress.yaml
  - namespace.yaml
