global:
  databasePassword: <path:kv/data/kubeclarity#db_password>
kubeclarity:
  ingress:
    enabled: true
    ingressClassName: tailscale
    hosts:
      - host: kubeclarity
    tls:
      - hosts:
          - kubeclarity
kubeclarity-trivy-server:
  enabled: true
kubeclarity-runtime-scan:
  vulnerability-scanner:
    analyzer:
      analyzerList: "syft gomod trivy"
      trivy:
        enabled: true
    scanner:
      scannerList: "grype trivy"
      trivy:
        enabled: true
