apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: harbor
    namespace: harbor
    releaseName: harbor
    valuesFile: values.yaml
    version: 1.16.0
    repo: https://helm.goharbor.io

patches:
  - target:
      version: v1
      group: apps
      kind: StatefulSet
      name: harbor-database
    path: patches/statefulset.yaml
  - target:
      version: v1
      group: apps
      kind: StatefulSet
      name: harbor-redis
    path: patches/statefulset.yaml
  - target:
      version: v1
      group: apps
      kind: StatefulSet
      name: harbor-trivy
    path: patches/statefulset.yaml
