apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: harbor
    namespace: harbor
    releaseName: harbor
    valuesFile: values.yaml
    version: 1.15.1
    repo: https://helm.goharbor.io
