apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: trivy-operator
    namespace: trivy-system
    releaseName: trivy-operator
    version: 0.21.4
    valuesFile: values.yaml
    repo: https://aquasecurity.github.io/helm-charts/
    includeCRDs: true
