apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: argo-admin.service-account-token
    namespace: argo-workflows

helmCharts:
  - name: cluster
    namespace: argo-workflows
    releaseName: argo-workflows-db
    valuesFile: values-argo-workflows-db.yaml
    version: 0.0.11
    repo: https://cloudnative-pg.github.io/charts
  - name: argo-workflows
    namespace: argo-workflows
    releaseName: argo-workflows
    valuesFile: values.yaml
    version: 0.42.5
    repo: https://argoproj.github.io/argo-helm

resources:
  - namespace.yaml
  - externalsecret.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - build-image.yaml
  - build-static-website.yaml

patches:
  - target:
      kind: Secret
      name: argo-admin.service-account-token
    patch: |-
      - op: add
        path: /type
        value: kubernetes.io/service-account-token
      - op: add
        path: /metadata/annotations
        value: {"kubernetes.io/service-account.name": "argo-admin"}
