controller:
  persistence:
    postgresql:
      host: argo-workflows-db-cluster-rw.argo-workflows.svc.cluster.local
      port: 5432
      database: argo-workflows
      tableName: argo_workflows
      userNameSecret:
        name: argo-workflows-credentials
        key: username
      passwordSecret:
        name: argo-workflows-credentials
        key: password
      ssl: true
      sslMode: require
  workflowDefaults:
    spec:
      serviceAccountName: argo-admin
workflow:
  serviceAccount:
    create: false
server:
  authModes:
    - sso
    - client
  sso:
    enabled: true
    issuer: https://<path:kv/data/infra/core/keycloak#hostname>/realms/master
    clientId:
      name: argo-server-sso
      key: client-id
    clientSecret:
      name: argo-server-sso
      key: client-secret
    redirectUrl: https://argo-workflows.<path:kv/data/infra/common#tailnet>/oauth2/callback
    scopes:
      - groups
    rbac:
      enabled: true
  ingress:
    enabled: true
    ingressClassName: tailscale
    hosts:
      - argo-workflows
    tls:
      - secretName: argoworkflows-tls
        hosts:
          - argo-workflows
artifactRepository:
  archiveLogs: false
  s3:
    accessKeySecret:
      name: argo-s3-credentials
      key: access_key
    secretKeySecret:
      name: argo-s3-credentials
      key: secret_key
    insecure: true
    bucket: argo-artifacts
    endpoint: http://minio.minio.svc.cluster.local
    region: ap-northeast-1
