apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: audit-tail
  labels:
    fluentbit.fluent.io/enabled: "true"
spec:
  tail:
    tag: audit.*
    path: /var/log/audit/kube/*.log
    parser: audit-parser
---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterParser
metadata:
  name: audit-parser
  labels:
    fluentbit.fluent.io/enabled: "true"
spec:
  json:
    timeFormat: "%Y-%m-%dT%H:%M:%S.%L%z"
    timeKey: "requestReceivedTimestamp"
---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: audit-es
  labels:
    fluentbit.fluent.io/enabled: 'true'
spec:
  es:
    bufferSize: 20MB
    generateID: true
    host: elasticsearch-es-http.default
    httpPassword:
      valueFrom:
        secretKeyRef:
          key: password
          name: elasticsearch-secrets
    httpUser:
      valueFrom:
        secretKeyRef:
          key: username
          name: elasticsearch-secrets
    logstashFormat: true
    logstashPrefix: audit-log
    port: 9200
    replaceDots: false
    suppressTypeName: 'true'
    timeKey: '@timestamp'
    traceError: true
    writeOperation: create
  matchRegex: (?:audit)\.(.*)
---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: k8s-audit
  labels:
    fluentbit.fluent.io/enabled: 'true'
spec:
  http:
    host: falco-k8saudit-webhook.falco.svc.cluster.local
    uri: /k8s-audit
    port: 9765
    format: json
  matchRegex: '*'
