monitoring:
  enabled: true
ingress:
  dashboard:
    ingressClassName: tailscale
    tls:
      - hosts:
          - ceph
cephClusterSpec:
  mon:
    allowMultiplePerNode: true

  mgr:
    allowMultiplePerNode: true
