monitoring:
  enabled: true
ingress:
  dashboard:
    host:
      name: ceph
    ingressClassName: tailscale
    tls:
      - hosts:
          - ceph
cephClusterSpec:
  mon:
    count: 1
    allowMultiplePerNode: true
  mgr:
    count: 1
    allowMultiplePerNode: true
  dashboard:
    ssl: false
