monitoring:
  enabled: true
ingress:
  dashboard:
    host:
      name: ceph
    ingressClassName: tailscale
    tls:
      - hosts:
          - ceph
cephClusterSpec:
  mon:
    count: 1
    allowMultiplePerNode: true
  mgr:
    count: 1
    allowMultiplePerNode: true
  dashboard:
    ssl: false
  resources:
    mgr:
      requests:
        cpu: "100m"
    mon:
      requests:
        cpu: "200m"
    osd:
      requests:
        cpu: "200m"
    prepareosd:
      requests:
        cpu: "100m"
    cleanup:
      requests:
        cpu: "100m"
cephFileSystems:
  - name: ceph-filesystem
    spec:
      metadataServer:
        resources:
          requests:
            cpu: "200m"
cephObjectStores:
  - name: ceph-objectstore
    spec:
      gateway:
        resources:
          requests:
            cpu: "200m"
