apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: rook-ceph
    repo: https://charts.rook.io/release
    version: 1.15.2
    releaseName: rook-ceph
    namespace: rook-ceph
    valuesFile: operator-values.yaml
  - name: rook-ceph-cluster
    repo: https://charts.rook.io/release
    version: 1.15.2
    releaseName: rook-ceph-cluster
    namespace: rook-ceph
    valuesFile: cluster-values.yaml

resources:
  - namespace.yaml

patches:
  - target:
      group: ceph.rook.io
      version: v1
      kind: CephFilesystem
      name: ceph-filesystem
      namespace: rook-ceph
    path: ./patches/fs_cpu_requests.yaml
  - target:
      group: ceph.rook.io
      version: v1
      kind: CephObjectStore
      name: ceph-objectstore
      namespace: rook-ceph
    path: ./patches/object_cpu_requests.yaml
  - target:
      group: storage.k8s.io
      version: v1
      kind: StorageClass
      name: ceph-block
    path: ./patches/disable_default.yaml
