apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: elasticsearch-es-elastic-user
    namespace: kube-system
    type: kubernetes.io/opaque
    envs:
      - bw-secrets/fluentd.env
resources:
  - fluentd-daemonset-elasticsearch.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
