apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: rabbitmq-cluster-operator
    namespace: rabbitmq
    releaseName: rabbitmq-operator
    version: 4.3.25
    repo: https://charts.bitnami.com/bitnami
    includeCRDs: true

resources:
  - rabbitmq.yaml
