apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: directus-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: directus-secret
    creationPolicy: Owner
    template:
      data:
        mariadb-root-password: "{{.root_password}}"
        mariadb-replication-password: "{{.replication_password}}"
        mariadb-password: "{{.password}}"
        ADMIN_PASSWORD: "{{.admin_password}}"
        KEY: "{{.key}}"
        SECRET: "{{.secret}}"
  dataFrom:
  - extract:
      key: infra/apps/directus
