apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: directus
    namespace: directus
    releaseName: directus
    valuesFile: values.yaml
    version: 1.0.5
    repo: https://directus-labs.github.io/helm-chart/
