apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: directus
    namespace: directus
    releaseName: directus
    valuesFile: values.yaml
    version: 1.1.0
    repo: https://directus-labs.github.io/helm-chart/

resources:
  - mariadb.yaml
  - externalsecret.yaml
  - database.yaml
  - user.yaml
  - grant.yaml
