apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: directus
spec:
  mariaDbRef:
    name: mariadb
  passwordSecretKeyRef:
    name: directus-secret
    key: mariadb-password
  maxUserConnections: 20
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
