adminEmail: <path:kv/data/infra/common#email>

ingress:
  enabled: true
  enableTLS: true
  className: tailscale
  hosts:
    - host: directus
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: directus-tls
     hosts:
       - directus
