adminEmail: <path:kv/data/infra/common#email>

ingress:
  enabled: true
  enableTLS: true
  className: tailscale
  hosts:
    - host: directus
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: directus-tls
     hosts:
       - directus

mariadb:
  enableInstallation: false
  auth:
    createSecrets: false
    existingSecret: directus-secret
    database: directus
    username: directus
  mariadbURL: mariadb.directus.svc.cluster.local
