apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argo-cd
spec:
  project: default
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.11.2
      chart: ingress-nginx
      plugin:
        name: custom-cmp
        parameters:
          - name: repo_url
            string: https://github.com/remikeat/cluster.git
          - name: repo_revision
            string: HEAD
          - name: repo_values
            string: argocd/applications/ingress-nginx/values.yaml
          - name: secrets
            string: ingress-nginx.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
