apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argo-cd
spec:
  project: default
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.23.0
      chart: base
    - repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.23.0
      chart: istiod
  destination:
    server: https://kubernetes.default.svc
    namespace: istio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
