apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argo-cd
spec:
  project: default
  sources:
    - repoURL: https://releases.rancher.com/server-charts/latest
      targetRevision: 2.9.2
      chart: rancher
      helm:
        valueFiles:
          - $repo/argocd/applications/rancher/values.yaml
    - repoURL: https://github.com/remikeat/cluster.git
      targetRevision: HEAD
      ref: repo
  destination:
    server: https://kubernetes.default.svc
    namespace: rancher
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
