apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/remikeat/cluster.git
    targetRevision: HEAD
    path: argocd/pipelines/argo-workflows/kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - kind: Secret
      name: argo-workflow.service-account-token
      namespace: argo-workflows
      jsonPointers:
        - /data
