apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-snapshotter
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/kubernetes-csi/external-snapshotter.git
      targetRevision: release-4.0
      path: client/config/crd
    - repoURL: https://github.com/kubernetes-csi/external-snapshotter.git
      targetRevision: release-4.0
      path: deploy/kubernetes/snapshot-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
