apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kiali-operator
    namespace: kiali-operator
    releaseName: kiali-operator
    valuesFile: values.yaml
    version: 1.89.0
    repo: https://kiali.org/helm-charts

resources:
  - https://raw.githubusercontent.com/kiali/helm-charts/refs/tags/v1.89.0/kiali-operator/crds/crds.yaml
