cr:
  create: true
  namespace: istio-system
  spec:
    auth:
      strategy: "anonymous"
    deployment:
      ingress:
        enabled: true
        class_name: "tailscale"
        override_yaml:
          spec:
            ingressClassName: tailscale
            rules:
              - http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: kiali
                          port:
                            number: 20001
            tls:
              - hosts:
                  - "kiali"
    external_services:
      grafana:
        enabled: true
        in_cluster_url: 'http://kube-prometheus-stack-grafana.kube-prometheus-stack'
        url: 'https://grafana.tail4d334.ts.net'
        auth:
          type: basic
          username: "admin"
          password: <path:kv/data/infra/grafana#password>
      prometheus:
        url: "http://kube-prometheus-stack-prometheus.kube-prometheus-stack:9090/"
      tracing:
        enabled: true
        use_grpc: true
        internal_url: "http://jaeger-query.observability:16685"
        external_url: "https://jaeger.tail4d334.ts.net"
