apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harvester
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/harvester/harvester.git
      targetRevision: v1.3.2-rc2
      path: deploy/charts/harvester
      helm:
        valueFiles:
          - $repo/argocd/vm/harvester/values.yaml
    - repoURL: https://github.com/remikeat/cluster.git
      targetRevision: HEAD
      ref: repo
  destination:
    server: https://kubernetes.default.svc
    namespace: harvester-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
