apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-app
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=zero"]
  generators:
  - list:
      elements:
      - app: core/cert-manager
      # - app: core/descheduler
      - app: core/istio
        namespace: istio-system
      - app: core/keycloak
      - app: core/kong
      - app: core/rancher
      - app: core/vault
      - app: storage/cloudnativepg
        namespace: cnpg-system
      # - app: storage/local-path-provisioner
      - app: storage/longhorn
        namespace: longhorn-system
      - app: storage/minio
        prune: false
      - app: storage/pgadmin
      - app: storage/rook-ceph
      - app: monitoring/crowdsec
      - app: monitoring/elastic
        namespace: elastic-system
      - app: monitoring/falco
      - app: monitoring/fluent
      - app: monitoring/grafana
        namespace: kube-prometheus-stack
      - app: monitoring/kiali
      - app: monitoring/kubeclarity
      - app: monitoring/metrics-server
      - app: monitoring/trivy
        namespace: trivy-system
      - app: messages/kafka
        prune: false
      - app: messages/kafka-ui
      - app: messages/rabbitmq
      - app: pipelines/harbor
      - app: pipelines/knative
      - app: pipelines/tekton
      - app: vm/kubevirt
      - app: vm/kubevirt-manager
      - app: vm/multus
      # - app: vm/external-snapshotter
      #   namespace: kube-system
      # - app: vm/harvester
      # - app: vm/system-upgrade-controller
      - app: apps/supabase
  template:
    metadata:
      name: '{{base .app}}-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/remikeat/cluster.git
        targetRevision: HEAD
        path: argocd/{{.app}}
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{default (base .app) .namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
  templatePatch: |
    spec:
      syncPolicy:
        automated:
          {{- if hasKey . "prune" }}
          prune: {{.prune}}
          {{- else }}
          prune: true
          {{- end }}
