apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-app
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/remikeat/cluster.git
    targetRevision: HEAD
    path: argocd/applications/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden-app
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/remikeat/cluster.git
    targetRevision: HEAD
    path: argocd/applications/bitwarden
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-app
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/remikeat/cluster.git
    targetRevision: HEAD
    path: argocd/applications/grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: remikeat-com-app
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/remikeat/cluster.git
    targetRevision: HEAD
    path: argocd/applications/remikeat.com
    plugin:
      name: custom-cmp
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-app
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/remikeat/cluster.git
    targetRevision: HEAD
    path: argocd/applications/tailscale
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
