apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/remikeat/cluster.git
    targetRevision: HEAD
    path: argocd/pipelines/knative
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: knative-eventing-operator-aggregated-stable
      jqPathExpressions:
        - .rules
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: knative-serving-operator-aggregated-stable
      jqPathExpressions:
        - .rules
