apiVersion: v1
kind: Namespace
metadata:
  name: debug
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
---
apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: debug
spec:
  restartPolicy: Never
  volumes:
  - name: var-folder
    hostPath:
      path: /var/
  - name: etc-folder
    hostPath:
      path: /etc/
  containers:
  - name: debug
    image: ubuntu
    securityContext:
      privileged: true
    volumeMounts:
    - name: var-folder
      mountPath: /node/var
    - name: etc-folder
      mountPath: /node/etc
    command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
