apiVersion: v1
kind: Namespace
metadata:
  name: debug
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
---
apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: debug
spec:
  restartPolicy: Never
  volumes:
  - name: var-folder
    hostPath:
      path: /var/
  - name: etc-folder
    hostPath:
      path: /etc/
  containers:
  - name: debug
    image: busybox
    securityContext:
      privileged: true
    volumeMounts:
    - name: var-folder
      mountPath: /node/var
    - name: etc-folder
      mountPath: /node/etc
    command: ["sh", "-c", "while true; do sleep 3600; done"]
