apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=zero"]
  generators:
  - list:
      elements:
      - app: monitoring/crowdsec
      - app: monitoring/elastic
        namespace: elastic-system
      - app: monitoring/falco
      - app: monitoring/fluent
      - app: monitoring/grafana
        namespace: kube-prometheus-stack
      - app: monitoring/jaeger
        namespace: observability
      - app: monitoring/kiali
      - app: monitoring/kubeclarity
      - app: monitoring/metrics-server
      - app: monitoring/open-telemetry
      - app: monitoring/trivy
        namespace: trivy-system
  template:
    metadata:
      name: '{{base .app}}-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/remikeat/cluster.git
        targetRevision: HEAD
        path: argocd/{{.app}}
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{default (base .app) .namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
