apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/remikeat/cluster.git
    targetRevision: HEAD
    path: argocd/applications
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
