apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cert-manager
    namespace: cert-manager
    releaseName: cert-manager
    valuesFile: values.yaml
    version: 1.15.3
    repo: https://charts.jetstack.io

resources:
  - letsencrypt_production.yaml
  - letsencrypt_staging.yaml
