apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: ingress-nginx
    namespace: ingress-nginx
    releaseName: ingress-nginx
    valuesFile: values.yaml
    version: 4.11.2
    repo: https://kubernetes.github.io/ingress-nginx
    additionalValuesFiles:
      - bw-secrets/ingress-nginx.yaml
