apiVersion: remikeat.com/v1
kind: GitGenerator
metadata:
  name: git-generator
  annotations:
    config.kubernetes.io/function: |
      exec: 
        path: ./git-generator.sh
spec:
  repoURL: https://github.com/supabase-community/supabase-kubernetes
  path: charts/supabase
  targetRevision: 17e14e812fd60a7b5eedb56bf3b359f42ebf91a4
  valuesFile: values.yaml
  name: supabase
  namespace: supabase
