service:
  type: ClusterIP
tls:
  force: true
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  hosts:
    - host: portainer.remikeat.com
      paths:
        - path: "/"
  tls:
    - hosts:
        - portainer.remikeat.com
      secretName: portainer-tls
