service:
  type: ClusterIP
tls:
  force: true
ingress:
  enabled: true
  ingressClassName: tailscale
  annotations:
    kubernetes.io/ingress.class: tailscale
  hosts:
    - host: portainer
      paths:
        - path: "/"
  tls:
    - hosts:
        - portainer
