service:
  type: ClusterIP
tls:
  force: false
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: portainer.remikeat.com
      paths:
        - path: "/"
  tls:
    - hosts:
        - portainer.remikeat.com
      secretName: portainer-tls
