apiVersion: v1
kind: Secret
metadata:
  name: vault-configuration
  namespace: argocd
stringData:
  VAULT_ADDR: http://vault.vault.svc.cluster.local:8200
  AVP_TYPE: vault
  AVP_AUTH_TYPE: token
  VAULT_TOKEN:
