apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: crowdsec
    namespace: crowdsec
    releaseName: crowdsec
    valuesFile: values.yaml
    version: 0.11.0
    repo: https://crowdsecurity.github.io/helm-charts

resources:
  - namespace.yaml
