apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: descheduler
    namespace: kube-system
    releaseName: descheduler
    valuesFile: values.yaml
    version: 0.30.1
    repo: https://kubernetes-sigs.github.io/descheduler/
