- op: replace
  path: /spec/gateway/resources/requests/cpu
  value: "100m"
- op: replace
  path: /spec/metadataPool/replicated/size
  value: 1
- op: remove
  path: /spec/dataPool/erasureCoded
- op: add
  path: /spec/dataPool/replicated
  value: {size: 1}
