apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kafka-ui
    namespace: kafka-ui
    releaseName: kafka-ui
    valuesFile: values.yaml
    version: 0.7.6
    repo: https://provectus.github.io/kafka-ui-charts
