yamlApplicationConfig:
  kafka:
    clusters:
      - name: yaml
        bootstrapServers: kafka-kafka-bootstrap.kafka:9092
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false
ingress:
  enabled: true
  ingressClassName: tailscale
  host: kafka-ui
  tls:
    enabled: true
    secretName: kafka-ui-tls
