apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://api.hub.tekton.dev/v1/resource/tekton/task/git-clone/0.9/raw
  - https://api.hub.tekton.dev/v1/resource/tekton/task/kaniko/0.6/raw
  - clone-build-push.yaml
