apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pg-backup-user
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: pg-backup-user
    creationPolicy: Owner
    template:
      data:
        CONSOLE_ACCESS_KEY: "{{.pg_backup_access_key}}"
        CONSOLE_SECRET_KEY: "{{.pg_backup_secret_key}}"
  dataFrom:
  - extract:
      key: infra/cloudnativepg
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argo-workflows-user
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: argo-workflows-user
    creationPolicy: Owner
    template:
      data:
        CONSOLE_ACCESS_KEY: "{{.access_key}}"
        CONSOLE_SECRET_KEY: "{{.secret_key}}"
  dataFrom:
  - extract:
      key: infra/argo-workflows
