apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: pg-backup-user
    literals:
      - CONSOLE_ACCESS_KEY=<path:kv/data/infra/cloudnativepg#pg-backup-access-key>
      - CONSOLE_SECRET_KEY=<path:kv/data/infra/cloudnativepg#pg-backup-secret-key>
  - name: argo-workflows-user
    literals:
      - CONSOLE_ACCESS_KEY=<path:kv/data/infra/argo-workflows#access_key>
      - CONSOLE_SECRET_KEY=<path:kv/data/infra/argo-workflows#secret_key>

helmCharts:
  - name: operator
    namespace: minio
    releaseName: operator
    valuesFile: operator-values.yaml
    version: 6.0.3
    repo: https://operator.min.io
  - name: tenant
    namespace: minio
    releaseName: tenant
    valuesFile: tenant-values.yaml
    version: 6.0.3
    repo: https://operator.min.io
