apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: operator
    namespace: minio
    releaseName: operator
    valuesFile: operator-values.yaml
    version: 6.0.3
    repo: https://operator.min.io
  - name: tenant
    namespace: minio
    releaseName: tenant
    valuesFile: tenant-values.yaml
    version: 6.0.3
    repo: https://operator.min.io

resources:
  - externalsecret.yaml
