apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: strimzi-kafka-operator
    namespace: kafka
    releaseName: kafka-operator
    version: 0.43.0
    repo: https://strimzi.io/charts/
    includeCRDs: true

resources:
  - namespace.yaml
  - kafkanodepool.yaml
  - kafka.yaml
