apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: eck-operator
    namespace: elastic-system
    releaseName: eck-operator
    version: 2.14.0
    repo: https://helm.elastic.co

resources:
  - configmap.yaml
  - elasticsearch.yaml
  - ingress.yaml
  - job.yaml
  - kibana.yaml
