apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: fluent-operator
    namespace: fluent
    releaseName: fluent-operator
    valuesFile: values.yaml
    version: 3.1.0
    repo: https://fluent.github.io/helm-charts
    includeCRDs: true

resources:
  - namespace.yaml
  - externalsecret.yaml
