apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: elasticsearch-secrets
    namespace: fluent
    type: kubernetes.io/opaque
    literals:
      - username=elastic
      - password=<path:kv/data/infra/elastic#password>

helmCharts:
  - name: fluent-operator
    namespace: fluent
    releaseName: fluent-operator
    valuesFile: values.yaml
    version: 3.1.0
    repo: https://fluent.github.io/helm-charts

resources:
  - namespace.yaml
