apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: elasticsearch-secrets
    namespace: fluent
    type: kubernetes.io/opaque
    literals:
      - username=elastic
      - password=<path:kv/data/infra/elastic#password>

resources:
  - namespace.yaml
  - crds.yaml
  - application.yaml
