containerRuntime: containerd
operator:
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 20Mi
fluentbit:
  crdsEnable: false
  enable: true
  output:
    es:
      enable: true
      host: elasticsearch-es-http.elastic-system
      suppressTypeName: On
      httpPassword:
        valueFrom:
          secretKeyRef:
            name: elasticsearch-secrets
            key: password
      httpUser:
        valueFrom:
          secretKeyRef:
            name: elasticsearch-secrets
            key: username
fluentd:
  crdsEnable: false
  enable: false
  output:
    es:
      enable: true
      host: elasticsearch-es-http.elastic-system
      suppressTypeName: On
      httpPassword:
        valueFrom:
          secretKeyRef:
            name: elasticsearch-secrets
            key: password
      httpUser:
        valueFrom:
          secretKeyRef:
            name: elasticsearch-secrets
            key: username
