apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-cmp-config
  namespace: argo-cd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: custom-cmp
    spec:
      init:
        command: [bash, -c]
        args:
          - |
            values.sh
      generate:
        command: [bash, -c]
        args:
          - |
            template.sh
