apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-secrets-cmp-config
  namespace: argo-cd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: helm-secrets-cmp
    spec:
      generate:
        command: [sh, -c]
        args:
          - |
            template.sh
