apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: pgadmin
    creationPolicy: Owner
    template:
      data:
        password: "{{.password}}"
  dataFrom:
  - extract:
      key: infra/pgadmin
