apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: pgadmin-config
    files:
      - servers.json

resources:
  - namespace.yaml
  - externalsecret.yaml
  - service.yaml
  - statefulset.yaml
  - ingress.yaml
