apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: pgadmin-config
    files:
      - servers.json
    behavior: replace

secretGenerator:
  - name: pgadmin
    literals:
      - password=<path:kv/data/pgadmin#password>

resources:
  - namespace.yaml
  - configmap.yaml
  - service.yaml
  - statefulset.yaml
  - ingress.yaml
