apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 61.8.0
      chart: kube-prometheus-stack
      plugin:
        name: custom-cmp
        parameters:
          - name: repo_url
            string: https://github.com/remikeat/cluster.git
          - name: repo_revision
            string: HEAD
          - name: repo_values
            string: argocd/applications/grafana/values.yaml
          - name: secrets
            string: grafana.yaml
          - name: args
            string: --skip-crds
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-prometheus-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
