apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 61.8.0
      chart: kube-prometheus-stack
      plugin:
        name: secret-config-plugin
        parameters:
          - name: repo_url
            value: https://github.com/remikeat/cluster.git
          - name: repo_revision
            value: HEAD
          - name: repo_path
            value: argocd/applications/grafana/
          - name: values
            value: values.yaml
          - name: secrets
            value: grafana.yaml
          - name: args
            value: --skip-crds
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-prometheus-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
