prometheus:
  prometheusSpec:
    scrapeInterval: 30s
    evaluationInterval: 30s
  service:
    annotations:
      tailscale.com/expose: "true"
      tailscale.com/hostname: "prometheus"
    type: LoadBalancer
