apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak-admin
    creationPolicy: Owner
    template:
      data:
        username: keycloak
        password: "{{.password}}"
  dataFrom:
  - extract:
      key: infra/keycloak
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak-credentials
    creationPolicy: Owner
    template:
      data:
        username: keycloak
        password: "{{.pg_password}}"
  dataFrom:
  - extract:
      key: infra/keycloak
