apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 1
  resources:
    requests:
      cpu: 100m
      memory: 500Mi
    limits:
      cpu: '1'
      memory: 2Gi
  db:
    vendor: postgres
    host: keycloakdb-cluster-rw.keycloak.svc.cluster.local
    database: keycloak
    usernameSecret:
      name: keycloak-credentials
      key: username
    passwordSecret:
      name: keycloak-credentials
      key: password
  hostname:
    hostname: https://<path:kv/data/infra/core/keycloak#hostname>
    # admin: https://keycloak-admin.tail4d334.ts.net
  http:
    httpEnabled: true
    tlsSecret: keycloak-tls
  ingress:
    enabled: false
  proxy:
      headers: forwarded
  bootstrapAdmin:
    user:
      secret: keycloak-admin
