apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cluster
    namespace: keycloak
    releaseName: keycloakdb
    valuesFile: values-keycloakdb.yaml
    version: 0.0.11
    repo: https://cloudnative-pg.github.io/charts

resources:
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.0.0/kubernetes/keycloaks.k8s.keycloak.org-v1.yml
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.0.0/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.0.0/kubernetes/kubernetes.yml
  - externalsecret.yaml
  - keycloak.yaml
  - ingress.yaml

patches:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: keycloak-operator
    path: patches/keycloak-operator.yaml
