apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secret-store
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: kv
      version: v2
      auth:
        tokenSecretRef:
          name: vault-configuration
          namespace: argocd
          key: VAULT_TOKEN
