apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: elasticsearch-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: elasticsearch-secrets
    creationPolicy: Owner
    template:
      data:
        ES_PASSWORD: "{{.password}}"
  dataFrom:
  - extract:
      key: infra/monitoring/elastic
