prometheus:
  prometheusSpec:
    scrapeInterval: 30s
    evaluationInterval: 30s
    additionalScrapeConfigs:
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: ${1}:${2}
          target_label: __address__
grafana:
  persistence:
    enabled: true
    storageClassName: longhorn
  dashboards:
    default:
      mesh-dashboard:
        gnetId: 7639
        revision: 227
        datasource: Prometheus
      service-dashboard:
        gnetId: 11829
        revision: 227
        datasource: Prometheus
      workload-dashboard:
        gnetId: 7636
        revision: 227
        datasource: Prometheus
      performance-dashboard:
        gnetId: 7630
        revision: 227
        datasource: Prometheus
      control-plane-dashboard:
        gnetId: 7645
        revision: 227
        datasource: Prometheus
      wasm-extension-dashboard:
        gnetId: 13277
        revision: 184
        datasource: Prometheus
