prometheus:
  prometheusSpec:
    scrapeInterval: 30s
    evaluationInterval: 30s
    additionalScrapeConfigs:
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: ${1}:${2}
          target_label: __address__
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
grafana:
  adminPassword: <path:kv/data/infra/monitoring/grafana#password>
  persistence:
    enabled: true
    storageClassName: longhorn
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      mesh-dashboard:
        gnetId: 7639
        revision: 227
        datasource: Prometheus
      service-dashboard:
        gnetId: 11829
        revision: 227
        datasource: Prometheus
      workload-dashboard:
        gnetId: 7636
        revision: 227
        datasource: Prometheus
      performance-dashboard:
        gnetId: 7630
        revision: 227
        datasource: Prometheus
      control-plane-dashboard:
        gnetId: 7645
        revision: 227
        datasource: Prometheus
      wasm-extension-dashboard:
        gnetId: 13277
        revision: 184
        datasource: Prometheus
      node-export-full:
        gnetId: 1860
        revision: 37
        datasource: Prometheus
      trivy-operator-dashboard:
        gnetId: 17813
        revision: 2
        datasource: Prometheus
        
  envFromSecrets:
    - name: elasticsearch-secrets
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: elasticsearch
          type: elasticsearch
          access: proxy
          url: http://elasticsearch-es-http.elastic-system.svc.cluster.local:9200
          basicAuth: true
          basicAuthUser: elastic
          jsonData:
            index: ks-logstash-log-*
            timeField: "@timestamp"
            tlsSkipVerify: true
          secureJsonData:
            basicAuthPassword: $ES_PASSWORD
