deschedulerPolicyAPIVersion: "descheduler/v1alpha1"

deschedulerPolicy:
  profiles:
    - name: ProfileName
      pluginConfig:
        - name: "LowNodeUtilization"
          args:
            thresholds:
              "cpu": 30
              "memory": 30
              "pods": 30
            targetThresholds:
              "cpu": 50
              "memory": 50
              "pods": 50
      plugins:
        balance:
          enabled:
            - "LowNodeUtilization"
