apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/rancher/local-path-provisioner/deploy?ref=v0.0.26
patches:
  - path: patches/configmap.yaml
  - path: patches/storageclass.yaml
  - path: patches/namespace.yaml
