apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubevirt/kubevirt/releases/download/v1.3.1/kubevirt-operator.yaml
  - https://github.com/kubevirt/kubevirt/releases/download/v1.3.1/kubevirt-cr.yaml
  - https://github.com/kubevirt/containerized-data-importer/releases/download/v1.60.2/cdi-operator.yaml
  - https://github.com/kubevirt/containerized-data-importer/releases/download/v1.60.2/cdi-cr.yaml

# patches:
#   - target:
#       version: v1
#       group: apps
#       kind: Deployment
#       name: cdi-operator
#     path: ./patches/image_patch.yaml
