apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  config:
    config-br-defaults:
      default-br-config: |
        clusterDefault:
          brokerClass: Kafka
          apiVersion: v1
          kind: ConfigMap
          name: kafka-broker-config
          namespace: knative-eventing
    config-tracing:
      backend: zipkin
      zipkin-endpoint: http://otel-collector-collector.open-telemetry:9411/api/v2/spans
      sample-rate: "0.1"
      debug: "true"
  workloads:
    - name: eventing-controller
      resources:
        - container: eventing-controller
          requests:
            cpu: 50m
            memory: 100M
    - name: eventing-webhook
      resources:
        - container: eventing-webhook
          requests:
            cpu: 50m
            memory: 50M
          limits:
            cpu: '1'
            memory: 1Gi
    - name: mt-broker-controller
      resources:
        - container: mt-broker-controller
          requests:
            cpu: 50m
            memory: 100Mi
    - name: mt-broker-filter
      resources:
        - container: filter
          requests:
            cpu: 50m
            memory: 100Mi
    - name: mt-broker-ingress
      resources:
        - container: ingress
          requests:
            cpu: 50m
            memory: 100Mi
