apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/knative/operator/releases/download/knative-v1.15.2/operator.yaml
  - knative-serving.yaml
  - knative-eventing.yaml
  - https://github.com/knative/serving/releases/download/knative-v1.15.2/serving-default-domain.yaml
  - https://github.com/knative-extensions/eventing-kafka-broker/releases/download/knative-v1.15.2/eventing-kafka-controller.yaml
  - https://github.com/knative-extensions/eventing-kafka-broker/releases/download/knative-v1.15.2/eventing-kafka-broker.yaml
  - config-br-defaults.yaml

patches:
  - path: patches/kafka-broker-config.yaml
