global:
  domain: "argocd.remikeat.com"
configs:
  params:
    server:
      insecure: true
server:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-production"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    extraTls:
      - hosts:
        - "argocd.remikeat.com"
        secretName: "argocd-tls"
repoServer:
  env:
    - name: GIT_ASKPASS
      value: /usr/local/bin/git_askpass.sh
    - name: GIT_USERNAME
      valueFrom:
        secretKeyRef:
          name: github-https
          key: username
    - name: GIT_TOKEN
      valueFrom:
        secretKeyRef:
          name: github-https
          key: password
  volumeMounts:
    - name: git-askpass
      mountPath: /usr/local/bin/git_askpass.sh
      subPath: git_askpass.sh
  volumes:
    - name: helm-values
      secret:
        secretName: helm-values
        optional: true
    - name: secret-config-plugin-config
      configMap:
        name: secret-config-plugin-config
    - name: cmp-tmp
      emptyDir: {}
    - name: git-askpass
      configMap:
        name: git-askpass
        defaultMode: 0555
        items:
          - key: git_askpass.sh
            path: git_askpass.sh
    - name: cmp-plugin
      configMap:
        name: cmp-plugin
        defaultMode: 0555
        items:
          - key: template.sh
            path: template.sh
  extraContainers:
    - name: secret-config-plugin
      command:
        - "/var/run/argocd/argocd-cmp-server"
      image: quay.io/argoproj/argocd
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          name: secret-config-plugin-config
          subPath: plugin.yaml
        - mountPath: /tmp
          name: cmp-tmp
        - mountPath: /helm-values
          name: helm-values
        - name: cmp-plugin
          mountPath: /usr/local/bin/template.sh
          subPath: template.sh
