global:
  domain: "argocd.remikeat.com"
configs:
  params:
    server:
      insecure: true
server:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      - cert-manager.io/cluster-issuer: "letsencrypt-production"
      - nginx.ingress.kubernetes.io/ssl-redirect: "false"
      - nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    extraTls:
      - hosts:
        - "argocd.remikeat.com"
        secretName: "argocd-tls"
