apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-upgrade-controller
  namespace: argo-cd
spec:
  project: default
  sources:
    - repoURL: https://github.com/rancher/system-upgrade-controller.git
      targetRevision: v0.13.4
      path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: system-upgrade-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
